name: 'qualtrics_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  qualtrics_source:
    # +schema: stg_qualtrics 
    +materialized: table
    tmp:
      +materialized: view

vars:
  qualtrics_source:
    user: "{{ source('qualtrics', 'user') }}"
    survey: "{{ source('qualtrics', 'survey') }}"
    question: "{{ source('qualtrics', 'question') }}"
    question_response: "{{ source('qualtrics', 'question_response') }}"
    question_option: "{{ source('qualtrics', 'question_option') }}"
    survey_response: "{{ source('qualtrics', 'survey_response') }}"
    sub_question: "{{ source('qualtrics', 'sub_question') }}"
    survey_version: "{{ source('qualtrics', 'survey_version') }}"
    survey_embedded_data: "{{ source('qualtrics', 'survey_embedded_data') }}"
    block: "{{ source('qualtrics', 'block') }}"
    block_question: "{{ source('qualtrics', 'block_question') }}"
    directory: "{{ source('qualtrics', 'directory') }}"
    directory_contact: "{{ source('qualtrics', 'directory_contact') }}"
    directory_mailing_list: "{{ source('qualtrics', 'directory_mailing_list') }}"
    contact_mailing_list_membership: "{{ source('qualtrics', 'contact_mailing_list_membership') }}"
    distribution: "{{ source('qualtrics', 'distribution') }}"
    distribution_contact: "{{ source('qualtrics', 'distribution_contact') }}"
    core_contact: "{{ source('qualtrics', 'core_contact') }}"
    core_mailing_list: "{{ source('qualtrics', 'core_mailing_list') }}"

    survey_pass_through_columns: []
    directory_pass_through_columns: []
    directory_contact_pass_through_columns: []
    distribution_pass_through_columns: []
    core_contact_pass_through_columns: []