name: 'qualtrics_source_integration_tests'
version: '0.1.1'
profile: 'integration_tests'
config-version: 2

vars:
  qualtrics_schema: qualtrics_source_integration_tests
  qualtrics__using_core_contacts: true
  qualtrics__using_core_mailing_lists: true
  
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  qualtrics_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    directory_contact:
      +column_types:
        phone: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
